version: '3.8'

services:
  # Backend API Service (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legal-citation-graph-backend-dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/citations.db
      - PDF_STORAGE_PATH=./data/pdfs
      - FEATURE_EXTERNAL_ENRICHMENT=false
      - MODEL_PROVIDER=openai
      - LOG_LEVEL=DEBUG
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
      - ./backend:/app/backend
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend Service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: legal-citation-graph-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/v1
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    command: ["npm", "run", "dev"]

volumes:
  data:

networks:
  default:
    name: legal-citation-graph-dev-network

